### ISSUE TITLE
Error trying to install v7 when v6 already installed

### ISSUE THREAD

**Issue by schrepel** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#1]
Hi, I'd had an issue trying to remove version 6.0 of FALM, got an email saying trying to just install v7 over it. After unblocking the ZIP and installing the package, got this during the install:

Could not upload file
System.Exception: Error unpacking extension... ---> System.IO.FileNotFoundException: Could not find file 'D:\inetpub\devclean\App_Data\e8ba893f-e751-4ce9-87c7-40e3062fd387\package.xml'. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn) at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver) at System.Threading.CompressedStack.runTryCode(Object userData) at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData) at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state) at System.Xml.XmlTextReaderImpl.OpenUrl() at System.Xml.XmlTextReaderImpl.Read() at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace) at System.Xml.XmlDocument.Load(XmlReader reader) at System.Xml.XmlDocument.Load(String filename) at umbraco.cms.businesslogic.packager.Installer.LoadConfig(String tempDir) at umbraco.cms.businesslogic.packager.Installer.Import(String InputFile) --- End of inner exception stack trace --- at umbraco.cms.businesslogic.packager.Installer.Import(String InputFile) at umbraco.presentation.developer.packages.Installer.uploadFile(Object sender, EventArgs e)

**Comment by afabri73** [comment]
Try to do this:
- Go to Developer/Packages/Installed packages
- Find "FALM Housekeeping"
- Open "FALM Housekeeping"
- On the right click on "Uninstall packages"
- Refresh page (or reloads nodes)

Repeat the uninstall procedure until FALM disappear from "Installed packages"
After that...try to reinstall the v7 version.

I now tried to uninstall and reinstall FALM and for me all is ok

**Comment by schrepel** [comment]
Was able to uninstall v6, and it disappeared from "installed packages"
after hitting Reload nodes.

But i still get the same error when I try and then install v7. Wondering if
I should do some additional restart or something.

Could not upload file
System.Exception: Error unpacking extension... --->
System.IO.FileNotFoundException: Could not find file
'D:\inetpub\devclean\App_Data\bb7d0526-5a51-477d-acc2-615ba1138283\package.xml'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at
System.IO.FileStream.Init(String path, FileMode mode, FileAccess access,
Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize,
FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean
bFromProxy, Boolean useLongPath, Boolean checkHost) at
System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options, String msgPath,
Boolean bFromProxy) at System.IO.FileStream..ctor(String path, FileMode
mode, FileAccess access, FileShare share, Int32 bufferSize) at
System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type
ofObjectToReturn) at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object
xmlResolver) at System.Threading.CompressedStack.runTryCode(Object
userData) at
System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode
code, CleanupCode backoutCode, Object userData) at
System.Threading.CompressedStack.Run(CompressedStack compressedStack,
ContextCallback callback, Object state) at
System.Xml.XmlTextReaderImpl.OpenUrl() at
System.Xml.XmlTextReaderImpl.Read() at
System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean
preserveWhitespace) at System.Xml.XmlDocument.Load(XmlReader reader) at
System.Xml.XmlDocument.Load(String filename) at
umbraco.cms.businesslogic.packager.Installer.LoadConfig(String tempDir) at
umbraco.cms.businesslogic.packager.Installer.Import(String InputFile) ---
End of inner exception stack trace --- at
umbraco.cms.businesslogic.packager.Installer.Import(String InputFile) at
umbraco.presentation.developer.packages.Installer.uploadFile(Object sender,
EventArgs e)

**Comment by schrepel** [comment]
Jeez, I am an idiot, sorry. Was trying to install from the
FALM_Housekeeping_v7_master.zip, rather than the
Falm_Housekeeping_7.0.0.0.zip file within that. All's good now.

**Comment by afabri73** [comment]
no problem...
download new version (I uploaded now) because I found a problem with translations. ;-)
