### ISSUE TITLE
Web Api + AngularJS for v7

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#10]
Is there a reason why not using Web Api controller and AngularJS in the package version for Umbraco?
or is it using same codebase?

**Comment by afabri73** [comment]
Hi,
compatibly with my work, I'm studying now Angular JS and its application to Umbraco. So I'm sorry the delay,  but I'm trying to update FALM Housekeeping...but considering that I'm very busy, it is very difficult for me update it in short time.
The project is open for collaboration then if anyone want help me, is well accepted. ;-)
