### ISSUE TITLE
Not Tracked

### ISSUE THREAD

**Issue by JohnBergman** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#11]
I couldn't find this in any documentation, but what does it mean when it says "not tracked" when dealing with media?

**Comment by afabri73** [comment]
Hi John,
Not Tracked means that it is a standard folder ("/media/nnnn/", where "nnnn" is a number) created by an upload from a data type that not save data into db.

Adriano

**Comment by JohnBergman** [comment]
Interesting, these are all files that were uploaded using the media section, so you are telling me that the default mechanism for uploading causes it to not be tracked?  That seems kind of suspicious to me :-).

**Comment by afabri73** [comment]
No...these are all files that were uploaded using "data type" (in content section) and were not saved into db.
These files I called "Not tracked" :-)
