### ISSUE TITLE
FALM throws error when attempting to view logs or check for orphaned media in Umbraco 7.6.3

### ISSUE THREAD

**Issue by petsmatt** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#12]
Selecting "Show Orphans To Delete" throws the following error:

Object does not match target type.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Reflection.TargetException: Object does not match target type.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[TargetException: Object does not match target type.]
   System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target) +14246737
   System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +151
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +96
   System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index) +37
   umbraco.DataLayer.CurrentConnectionUsing.get_Connection() +93
   umbraco.DataLayer.SqlHelpers.SqlServer.SqlServerHelper.ExecuteReader(String commandText, SqlParameter[] parameters) +270
   umbraco.DataLayer.SqlHelper`1.ExecuteReader(String commandText, IParameter[] parameters) +115

[SqlHelperException: Umbraco Exception (DataLayer): SQL helper exception in ExecuteReader]
   umbraco.DataLayer.SqlHelper`1.ExecuteReader(String commandText, IParameter[] parameters) +304
   FALMHousekeepingMediaManager.cleanupMediaFS.btnCheckOrphan_Click(Object sender, EventArgs e) +1066
   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +11750641
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +150
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +6016

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1055.0

**Comment by afabri73** [comment]
I think there is a problem with the package installation.
Current version function properly until Umbraco 7.5.14
I haven't yet tested the package with Umbraco 7.6+

Have you tried to uninstall and reinstall the package?
Which Umbraco Version do you use?
Which kind of DB do you use?

I look forward to your reply.
Regards
Adriano

_Only for Info...a new release will be released (i think) by the end of the month.
This version is completely rewrite to use angularJS.
It is more faster and more reliable than the current version and have also a tracelog viewer._

**Comment by afabri73** [comment]
New version released.
Uninstall all previous version of FALM Housekeeping and try with the new version
