### ISSUE TITLE
Umbraco 7.6.3 New Install Test - DataReader Error

### ISSUE THREAD

**Issue by codeguise** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#13]
Running in IIS Express in VS Debug. Setup with MSSQL Database.

When attempting to open the Media -> Cleanup File System we get an error:

There is already an open DataReader associated with this Command which must be closed first.

Stack Trace:

[InvalidOperationException: There is already an open DataReader associated with this Command which must be closed first.]
   System.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command) +1544253
   System.Data.SqlClient.SqlConnection.ValidateConnectionForExecute(String method, SqlCommand command) +89
   System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async) +268
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) +118
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) +64
   System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) +161
   System.Data.SqlClient.SqlCommand.ExecuteReader() +99
   umbraco.DataLayer.SqlHelpers.SqlServer.SqlServerHelper.ExecuteReader(String commandText, SqlParameter[] parameters) +271
   umbraco.DataLayer.SqlHelper`1.ExecuteReader(String commandText, IParameter[] parameters) +83

[SqlHelperException: Umbraco Exception (DataLayer): SQL helper exception in ExecuteReader]
   umbraco.DataLayer.SqlHelper`1.ExecuteReader(String commandText, IParameter[] parameters) +245
   FALMHousekeepingMediaManager.cleanupMediaFS.btnCheckOrphan_Click(Object sender, EventArgs e) +1782
   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +9712582
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +204
   System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +12
   System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +15
   System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +35
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1639

**Comment by afabri73** [comment]
New version released.
Uninstall all previous version of FALM Housekeeping and try with the new version
