### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by vladox** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#16]
Hi
Is there a Nuget Package available? In case there isn't would you like me to contribute with one?
Best
Vlad

**Comment by CasperTDK** [comment]
👍

**Comment by afabri73** [comment]
Hi vladox, at this time there isn't a NuGet Package.
If you want, you can contribute to create one.
Thank you

**Comment by afabri73** [comment]
Only for info...I already created and published the NuGet Package ;-)
