### ISSUE TITLE
Essential views not included in the install

### ISSUE THREAD

**Issue by FootswordTechnologies** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#2]
Hi,

I have just installed the latest version of FALM Housekeeping (7.0.0) in Umbraco 7.2.8. I cannot access any of the views. I get error 404 on views/FALMHousekeepting/edit.html . I do not have a copy of this file in my website. How do I get hold of it?

**Comment by FootswordTechnologies** [comment]
Just uninstalled and reinstalled from the downloaded zip file here. Exactly the same. I can't click on any of the main headers, such as "Media" without getting error 404 asking for views/falmhousekeeping/edit.html.
If I click on Media/Cleanup File system, I just get one blank button on the right hand part of the dashboard. It isn't much better for the logs, although I do get a pretty plain form with no content and a blank button.
At the moment, the utility is not usable.

**Comment by afabri73** [comment]
Yes this is a known issue.
I tried to resolve this issue but I still working on it.
I cannot completely remove the header link.
Now I'm trying to assign a function to open the first child (WIP).
I hope to upload a new version ASAP

Anyway...remember that to use Housekeeping you must before expand the sections (Logs, Media, Users, Versions) by clicking on arrow on the left of the section name.

Adriano

**Comment by FootswordTechnologies** [comment]
Yes, I think you can tell I did that, or I would not have seen a page with
one blank button on it for the media section

**Comment by afabri73** [comment]
Fixed ;-)

**Comment by FootswordTechnologies** [comment]
Aha! Now I have just laboriously removed all the media references I don't
want, using mediaservice. Is it possible I could use FALM to lose the media
files?

**Comment by afabri73** [comment]
Sorry I didn't understand.
Could you better explain the problem?

**Comment by FootswordTechnologies** [comment]
This is what the media section of your tool does, isn't it? Removes files
from media that have been deleted in the database?

Amanda

**Comment by FootswordTechnologies** [comment]
​

**Comment by FootswordTechnologies** [comment]
That is what I see when I click on the media/cleanup file system. What do I
do with that?

Amanda

**Comment by afabri73** [comment]
With the Media Cleanup you can delete all existing files on filesystem in the folder "/Media/", which is not referenced in the DB, without touching any custom folders

**Comment by FootswordTechnologies** [comment]
Just an empty button with no instructions on it? Is it supposed to look
like that? Have you seen the screenshot?

**Comment by afabri73** [comment]
I don't see any screenshot. Can you resend me?

**Comment by FootswordTechnologies** [comment]
Sorry, here it is. I've clicked the mysterious button and I am getting a
wait symbol (circular gif). something is happening. But just a small blank
button is surely not how it is meant to be?

**Comment by afabri73** [comment]
no screenshot in your message. :-/

**Comment by FootswordTechnologies** [comment]
I can see it in my message. Anyway. As I said yesterday, all the media pane
shows is one grey button with no writing on it. I have pressed it and half
an hour later it is still going. My media file has 33,000 items and I only
need 400. I have used mediaservice to delete the rest. Since your tool give
no feedback or instructions, I do not know what it is doing.

**Comment by FootswordTechnologies** [comment]
I have uninstalled it. I need a tool which will delete media files that I
have deleted from the database (orphan files). I can't see your tool doing
anything of the sort. Most disappointing.

**Comment by afabri73** [comment]
ok...I don't know why you are this problem.
I try to explain what the Media Cleanup do.

When you open "Cleanup File System", you must click (on the right panel) on the button **Show orphans to delete**

After that you receive various information: a table with list of orphans files and another one with the ignored files on deletion

After those table you have a button to start deletion.

After some time (normally less a 2 minutes...but sometimes more, depends of number of files to delete, but normally not more than 30 minutes) you must see a message that confirm the deletion completed.

If this doesn't happen, I think that there is another problem not addicted to my tool. I now tried to install my tool in a test website and the Media Cleanup function properly.

I don't know why you have those problems.

Adriano

**Comment by FootswordTechnologies** [comment]
There is only one button and it has no title on it and no instructions. The
tool sounds great but it is not offering any of those options.

**Comment by afabri73** [comment]
no...Amanda...there must be an explanation and I want to understand and solve the problem!!!
This has become a challenge :-)

1 ) - You tell me that you not see any message or text in the right panel...right?

OK The problem can be the dictionary.
Can you check if the dictionary have a FALM section with all items?
If yes: can you check if all entries are filled or empty?
If no: this is why you don't see any text in the Media Cleanup Page :-(

**Comment by afabri73** [comment]
Good Morning Amanda,
You resolved?
The new version of FALM Hosekeeping (v7.0.0.1) now contains the English (United States) and the Italian languages with translations.
If you use another language, I will add it in my package on next release.

Bye
Adriano
