### ISSUE TITLE
Can't see the menu

### ISSUE THREAD

**Issue by Sven-T** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#22]
I've installed version 7.6.0.0 FALM and I'm using Umbraco 7.5.11. When I give my user permission to see the section, the section icon appears, but when I click it I only see the Dashboard and not the menu. Can you help me out in finding a solution?

**Comment by Sven-T** [comment]
Never mind. I installed it in another version of Umbraco and noticed that the line  below was missing in the trees.config

    `<add initialize="true" sortOrder="0" alias="housekeeping" application="FALM" title="Menu" iconClosed="icon-folder" iconOpen="icon-folder-open" type="FALM.Housekeeping.HKTreeController, FALM.Housekeeping" />`

After adding it everything started working as expected.

**Comment by afabri73** [comment]
Hi Sven,
now you shouldn't need that directive.
I didn't try it on Umbraco v7.5.11 but only with v7.5.14 and higher and it works perfectly for all versions.
I don't understand why you have this problem.
Have you check the permissions on this file (trees.config)...it cold be the problem.
I also saw the first release of my package (after the restyling) and there wasn't the directive. 

And no...I haven't receive issues like this from others users...until now. :-)
