### ISSUE TITLE
Unrecognized element 'EnablePropertyValueConverters'.

### ISSUE THREAD

**Issue by samsam321** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#24]
Umbraco Version v7.6.3

After install FALM via nuget, first error is the HtmlAgilityPack dependency , fixed this error after update-package HtmlAgilityPack

Then the this error displayed

![image](https://user-images.githubusercontent.com/5652498/30729956-e78d7e66-9f95-11e7-917a-a1546e3b6d4f.png)

Could you help with that ?Thanks

**Comment by Elven11** [comment]
I am having issues with it on 7.6.3 as well, as it seems to reduce you to older version of Umbraco, and it breaks all kind of stuff for me.

**Comment by afabri73** [comment]
I'm using the last version of my package in three different websites with Umbraco v7.6.1 and I haven't problems
I'll try FALM HK with a new Umbraco installation v7.6.2+

**Comment by afabri73** [comment]
Hi,
I installed and tested last version of FALM Housekeeping (v7.6.0.3) with this Umbraco installations:
- v 7.5.14: everything works properly
- v 7.6.1: everything works properly
- v 7.6.8: everything works properly
- v 7.7.1: everything works properly

Please check your installation.
You can try to remove all FALM Housekeeping installations and reinstall the last one.

I look forward to your reply.
Adriano
