### ISSUE TITLE
Cleanup by date

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#26]
I have installed v7.6.0.3 in a Umbraco v7.5.8, but it seems cleanup by date is no longer available as in the older version?

![image](https://user-images.githubusercontent.com/2919859/31545297-fe8ed53a-b01e-11e7-8756-829402c6cae0.png)

Btw. the link to the source code from our.umbraco.org is broken.
https://our.umbraco.org/projects/backoffice-extensions/falm-housekeeping/

**Comment by afabri73** [comment]
Hi bjarnef,
yes the Cleanup by Date function is no longer available in the new version.

Thank you for the support on the source code link.
I changed it.

Adriano

**Comment by bjarnef** [comment]
Any reason why it can't have a cleanup by date?
The input for cleanup by count should really use `<input type="number" min="0" pattern="[0-9]*" />`
http://bradfrost.com/blog/mobile/better-numerical-inputs-for-mobile-forms/

**Comment by afabri73** [comment]
I have had very big problems with this function and angularjs and for now I decided to create a button to remove all version.
I planned to re-enable it...but for now I have the same problems

Adriano
