### ISSUE TITLE
Issues with highlight of selected node

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#27]
It seems there are some issues with highlight of selected node. I think the `syncTree` is in a wrong place, e.g. /umbraco/#/FALM/housekeeping/edit/versions-manager doesn't trigger syncTree correct, so refreshing page has the nodes collapsed.

**Comment by afabri73** [comment]
I'll check it.

Thank you for the support
Adriano

**Comment by afabri73** [comment]
Hi Bjarne,
problem solved.
You can download the new v7.6.0.8 version.

Adriano
