### ISSUE TITLE
Browsing to "File System cleanup" start searching

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#28]
When I browse to "File System cleanup" is start searching and ends with the message below. Why is that? Why not add a button, so it first start searching, when the user wants to search as in the older version :)

![image](https://user-images.githubusercontent.com/2919859/31545475-df1e2baa-b01f-11e7-8a84-998db6946fe3.png)

![image](https://user-images.githubusercontent.com/2919859/31545535-20c15de8-b020-11e7-8ec3-3fd8a23a4934.png)

**Comment by afabri73** [comment]
Hi,
I received a lot of request about this argument in which most of users/developers ask me to auto search orphans on opening Media Folder Management.
so I decided to automate this function.

Adriano

**Comment by bjarnef** [comment]
Okay, I just think that a is bad user expirience when you want to browse the different nodes and og then trigger the action, when loading the view- you could always just click a button to trigger the action. I tested it with a multisite solutions with a large media archieve and it was running for a while just because I browsing to the node.

**Comment by afabri73** [comment]
Ok...I really think the same thing, infact in my personal release I disabled this function and I enabled the manual search action.
However, I think that I could  come back to the original function in next release.

I'll think about it.
Adriano
