### ISSUE TITLE
YSOD with v7.2

### ISSUE THREAD

**Issue by EssyGreen** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#3]
Just installed (v7.0.0.1) on v7.2.6 and get YSOD "Keyword not supported:'flush interval'" when trying to view Show Logs, Cleanup Logs or Delete Users. All other options (Cleanup File System, Show Versions etc) show screens with absolutely no data when selected and then show the same YSOD when trying to search.

![image](https://cloud.githubusercontent.com/assets/1406619/13026558/b650d9f6-d223-11e5-8dee-e301d11e6f5c.png)

**Comment by afabri73** [comment]
Hello,
I tried it on Umbraco v7.1.x installation and it work.
I will try Housekeeping on umbraco v7.2.x, v7.3.x and v7.4.x installations asap.

Stay tuned. :-)

Thank you for your support
Adriano

**Comment by EssyGreen** [comment]
Any news on this?

Sarah

On 15/02/2016 09:18, Adriano Fabri wrote:

> Hello,
> I tried it on Umbraco v7.1.x installation and it work.
> I will try Housekeeping on umbraco v7.2.x, v7.3.x and v7.4.x 
> installations asap.
> 
> Stay tuned. :-)
> 
> Thank you for your support
> Adriano
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/FALM-Umbraco-Projects/FALM-Housekeeping-v7/issues/3#issuecomment-184127839.

## 

Sarah Green
Brighter Working Limited
Registered in England and Wales No. 5953659
Registered Office: West Great Hole, Lapford, Crediton EX17 6NB

**Comment by afabri73** [comment]
Sorry for delay...
I think I understand (perhaps) what is the problem.
I tried to replicate your error (from Umbraco 7.0 to 7.4) and I find it only in this case:
- I downloaded FALM Housekeeping v7.0.0.1
- **I haven't removed the security block on this zip file**
- I tried to install the package
- I tried log feature and I receive the YSOD like your.

Please try to do this:
- Download again FALM Housekeeping v7.0.0.1
- Uninstall actual FALM Housekeeping from your website
- Right click on FALM_Housekeeping_7.0.0.1.zip and click on properties
- Go down at the end of the properties window (tab General)
- Check or push on "Unblock"
- Click Apply, then OK
- Try to reinstall FALM Housekeeping in your website
- Try to use log feature.

I think it should work.

I look forward to your reply
Adriano

**Comment by EssyGreen** [comment]
Hiya Adriano,

Many thanks for looking into this ... Unfortunately your solution didn't 
work ...

Previously I had just installed direct from the "Packages" section in 
Umbraco but following your suggestion I downloaded it separately and 
installed it as a local package. The downloaded file didn't appear to be 
blocked (there was no "Block/Unblock" option in the Properties tabs, 
just the "Archive" checkbox which I unchecked to be on the safe side). 
All appeared to install correctly (no errors reported) but as before as 
soon as I navigate to Logs I get the YSOD.

I had a look in the Dictionary and all items are set up for Italian and 
English (United States) but English (United Kingdom) is all blank and 
showing a warning for all items. (I also noticed that when I uninstalled 
FALM Housekeeping it came up with errors related to the Dictionary 
items) ... Could this be related? (It would seem probable that this is 
the reason why for example, the "Show Versions" page is all blank tho' 
I'm not sure it would cause the YSOD in the Logs and other sections?

Best Wishes

Sarah

On 02/03/2016 11:07, Adriano Fabri wrote:

> Sorry for delay...
> I think I understand (perhaps) what is the problem.
> I tried to replicate your error and I find it only in this case:
> - I downloaded FALM Housekeeping v7.0.0.1
> - _I haven't removed the security block on this zip file_
> - I tried to install the package
> - I tried log feature and I receive the YSOD like your.
> 
> Please try to do this:
> - Download again FALM Housekeeping v7.0.0.1
> - Uninstall actual FALM Housekeeping from your website
> - Right click on FALM_Housekeeping_7.0.0.1.zip and click on properties
> - Go down at the end of the properties window (tab General)
> - Check or push on "Unblock"
> - Click Apply, then OK
> - Try to reinstall FALM Housekeeping in your website
> - Try to use log feature.
> 
> I think it should work.
> 
> I look forward to your reply
> Adriano
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/FALM-Umbraco-Projects/FALM-Housekeeping-v7/issues/3#issuecomment-191190026.

## 

Sarah Green
Brighter Working Limited
Registered in England and Wales No. 5953659
Registered Office: West Great Hole, Lapford, Crediton EX17 6NB

**Comment by afabri73** [comment]
Uhmmm...I don't think so.
I installed 5 instances of Umbraco (v7.0 - v7.1 - v7.2 - v7.3 - v7.4) and only 2 admin user have the italian language...all 3 others, have en-GB
In all instances my package function properly.

I don't understand where is the problem and I don't know how to solve it...but there is absolutely something in your umbraco (or FALM) installation which generates the problem.

If I'll find another possible solution, I'll send you.

Bye

**Comment by EssyGreen** [comment]
Hiya Adriano,

I think it might be that I'm using SQLCE ... Am just reinstalling with 
proper SQL Db and will let you know if this solves it.

Best Wishes

Sarah

On 02/03/2016 14:07, Adriano Fabri wrote:

> Uhmmm...I don't think so.
> I installed 5 instances of Umbraco (v7.0 - v7.1 - v7.2 - v7.3 - v7.4) 
> and only 2 admin user have the italian language...all 3 others, have en-GB
> In all instances my package function properly.
> 
> I don't understand where is the problem and I don't know how to solve 
> it...but there is absolutely something in your umbraco (or FALM) 
> installation which generates the problem.
> 
> If I'll find another possible solution, I'll send you.
> 
> Bye
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/FALM-Umbraco-Projects/FALM-Housekeeping-v7/issues/3#issuecomment-191249820.

## 

Sarah Green
Brighter Working Limited
Registered in England and Wales No. 5953659
Registered Office: West Great Hole, Lapford, Crediton EX17 6NB

**Comment by EssyGreen** [comment]
Hiya Adriano,

Yes that was it ... reinstalled with MSSQL and it's working fine :)

Many thanks for your help

Best Wishes

Sarah

On 02/03/2016 14:58, Sarah Green wrote:

> Hiya Adriano,
> 
> I think it might be that I'm using SQLCE ... Am just reinstalling with 
> proper SQL Db and will let you know if this solves it.
> 
> Best Wishes
> 
> Sarah
> 
> On 02/03/2016 14:07, Adriano Fabri wrote:
> 
> > Uhmmm...I don't think so.
> > I installed 5 instances of Umbraco (v7.0 - v7.1 - v7.2 - v7.3 - v7.4) 
> > and only 2 admin user have the italian language...all 3 others, have 
> > en-GB
> > In all instances my package function properly.
> > 
> > I don't understand where is the problem and I don't know how to solve 
> > it...but there is absolutely something in your umbraco (or FALM) 
> > installation which generates the problem.
> > 
> > If I'll find another possible solution, I'll send you.
> > 
> > Bye
> > 
> > —
> > Reply to this email directly or view it on GitHub 
> > https://github.com/FALM-Umbraco-Projects/FALM-Housekeeping-v7/issues/3#issuecomment-191249820.
> 
> ## 
> 
> Sarah Green
> Brighter Working Limited
> Registered in England and Wales No. 5953659
> Registered Office: West Great Hole, Lapford, Crediton EX17 6NB

## 

Sarah Green
Brighter Working Limited
Registered in England and Wales No. 5953659
Registered Office: West Great Hole, Lapford, Crediton EX17 6NB

**Comment by afabri73** [comment]
Thank you too...I will start working immediately to make even the project compatible also with SQLCE
