### ISSUE TITLE
NuGet package should add assembly

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#33]
I installed the package via NuGet https://www.nuget.org/packages/FALMHousekeeping/7.6.0.5 but it add several files to `/App_Code`.

Why not compile the code and include a single dll in your package?

![image](https://user-images.githubusercontent.com/2919859/31587887-e780a7f2-b1e9-11e7-911c-e3b236c6c26c.png)

It seems you have include the entire project in your NuGet package.
![image](https://user-images.githubusercontent.com/2919859/31588034-6a365ac8-b1ec-11e7-9b0e-5f5ac90268af.png)

In the Umbraco package you do include an assembly.

![image](https://user-images.githubusercontent.com/2919859/31587987-c8c85560-b1eb-11e7-9b71-a236ac72033a.png)

![image](https://user-images.githubusercontent.com/2919859/31587991-d571f1a4-b1eb-11e7-89e8-d187ac8044ea.png)

Furthermore I wonder why you modify core language files in latest version (since it is target to Umbraco 7.5+), which hasn't been necessary since pre Umbraco 7.3

![image](https://user-images.githubusercontent.com/2919859/31588007-0f64820a-b1ec-11e7-91ef-6af1426d33e9.png)

You are also including a resource file, which is just an empty file :)
https://github.com/FALM-Umbraco-Projects/FALM-Housekeeping-v7/blob/master/FALMHousekeeping/App_Plugins/FALM/housekeeping.resource.js

**Comment by bjarnef** [comment]
Any change you have time to update the NuGet package to include the assembly instead?
I prefer to install via NuGet when packages are available there, but I don't want to include all these files in `/App_Code` in our project.

I have tested with latest version 7.6.0.6

**Comment by afabri73** [comment]
Hi bjarnef,
I created the NuGet package to allow developers to use and/or extend my package.
So...in your solution you can have a project for FALM HK and a project with your umbraco installation.
If you want, I can give you only the assembly but I cannot publish only the assembly...this isn't the purpose of my nuget package :-)
I'm sorry...

**Comment by bjarnef** [comment]
@afabri73 I still think it is ideal to build the NuGet package which includes the dll. That's the way most of other Umbraco packages does it.

If developers want to customize FALM HK, they can always fork the repository and compile a custom dll or you could create base classes / interfaces for stuff people want to or are allowed to extend. E.g. Umbraco has `UmbracoApiController` and `SurfaceController`, even classes to extend with a custom section, which you use https://github.com/FALM-Umbraco-Projects/FALM-Housekeeping-v7/blob/master/FALMHousekeeping/Applications/HKApplication.cs#L11-L12

If there a specific feature or bug, developers can always submit a PR for this as well 👍

**Comment by afabri73** [comment]
Bjarne,
this is my first approach to the NuGet world and I'm still learning.
What you say is really true and I have no reason to dispute it.
When I created the NuGet package of FALM HK I imagined what could be his purpose and I made the current choice.
I don't exclude that I can decide to change my choice...thanks also to users support.

So I thank you for the suggestion and I assure you that I will think well of everything we said

Adriano

**Comment by bjarnef** [comment]
I haven't build many NuGet package either, but I often learn from other package developers on our.umbraco.org 😃

If they didn't compile the classes to a dll, I guess we could end up with many class files in `/App_Code` and probably some of them would conflict with each other unless they have a unique prefix.

**Comment by afabri73** [comment]
Hi Bjarne,
I thought a lot about what you said and I think it's the best thing to do.

If I well understand, I should delete all the source code from the NuGet package and leave only the `App_Plugins/FALM` folder and FALM HK dll

Right? OK i'll done it.
Today or tomorrow you will find the new NuGet Package Version.

Thank you for the support
Bye

**Comment by bjarnef** [comment]
@afabri73 yes, it should be fine if you include the `/App_Plugins/FALM/` folder and the assembly (dll).

**Comment by afabri73** [comment]
I've done it ;-)
