### ISSUE TITLE
Cleanup by count show error message

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#35]
When I trigger cleanup by count and set count to 20, then then the request fails.

![image](https://user-images.githubusercontent.com/2919859/31600730-d17b3ef4-b257-11e7-92f8-07265d01daa5.png)

![image](https://user-images.githubusercontent.com/2919859/31600817-1897db58-b258-11e7-9300-b6dff25839dc.png)

I don't see any error message or errors in log file.

**Comment by bjarnef** [comment]
Strange, after some time I got this:

![image](https://user-images.githubusercontent.com/2919859/31601191-45dd82ec-b259-11e7-9bed-b8df582dc7f7.png)

**Comment by bjarnef** [comment]
Okay, it might work, but it just show the error message from start, no loading indicator and then the response after about 20 seconds.

**Comment by bjarnef** [comment]
I had a look at both the table view and db table for homepage node after running this and can confirm that it has cleared to 20 versions.
However it is a UI issue with missing preloader being shown and error message that is visible when no errors occurs.

**Comment by afabri73** [comment]
Hi,
I just published a new version of FALM HK.
This version includes various fixes (bugs and UI)
I tried this version with Umbraco v7.6+ and v7.7+ and I haven't the explained issue.
Please uninstall all FALM HK packages from your Umbraco website, reinstall the new one (FALM Housekeeping v7.7.0.0) and check if you have the same problem.
Thank you for the support.
Adriano
