### ISSUE TITLE
Fails to install v7.6.0.6

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#37]
I tried to install v7.6.0.6, but it fails during install. Our project is running on Umbraco 7.5.8 and I also have same issues in a clean Umbraco 7.5.8 install.

I had no issues when installing v.7.6.0.3

![image](https://user-images.githubusercontent.com/2919859/31955753-9e5d6798-b8e9-11e7-8776-3a05aaa81b12.png)

**Comment by afabri73** [comment]
Hi Bjarne,
this is very strange.
I have installed FALM HK on several Umbraco versions (7.5, 7.6 and 7.7 ... and relative subversions) and I have never encountered in that problem.
I still have two websites with Umbraco v7.5.14 and v7.5.11 and I haven't any problems.

Perhaps that particular version of Umbraco has something that conflicts with FALM HK.

I'll try to figure out what is the problem but please tell me if you find a solution before me

**Comment by afabri73** [comment]
It seems that some other person have the same error with other packages and with only some Umbraco versions.
Most of them solved by installing the next version of Umbraco.

I'll check for other solutions

**Comment by TFAstudio** [comment]
We have gone through an upgrade process to bring our Umbraco up to this decade ;)

We have upgraded from Umbraco v4 to Umbraco v7  After this process, we have decided to use FALM Housekeeping to finalize the clean up process.  However, when installing FALM v7 via the Umbraco Back Office, the process halts with a generic error.  When I access our site after installing via the Umbraco Back Office or via ZIP, we get the following error:

> `Could not load all types from "FALM.Housekeeping, Version=7.6.0.8, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
> . System.TypeLoadException on umbraco.interfaces.IDiscoverable: Could not load type 'umbraco.interfaces.IDiscoverable' from assembly 'interfaces, Version=1.0.6345.13056, Culture=neutral, PublicKeyToken=null'.`

What is going on here and how can I mitigate this error and use FALM with Umbraco v7.15.4?

**Comment by afabri73** [comment]
Hi TFAStudio,
which FALM HK version did you installed?
Have you prevously uninstall any other old FALM HK versions?
I'm trying to replicate the error on my clean Umbraco v7.5.14 but I haven't any problems during installation.

**Comment by afabri73** [comment]
Hi to all,
I tried to replicate the error on Umbraco v7.5.14 and finally I've done it.
You can uninstall any version of FALM HK and install temporaly the v7.6.0.3 that not thrown that exception.

The actual v7.6.0.8 have no problem with Umbraco v7.6+, v7.7+ and v7.5+ (until v7.5.13)

I'm now investigating to solve the problem.

**Comment by afabri73** [comment]
At this moment I didn't found solutions, so I republished the 7.6.0.3 version which is compatible with Umbraco v7.5.14

I close this issue but I will continue to investigate if there is a solution.
If i'll find it, I'll add a comment here.

Adriano
