### ISSUE TITLE
v7.0.0.1 - For Umbraco v7+ appearance?

### ISSUE THREAD

**Issue by vcd195** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#38]
Hi, 
We haven't upgraded to umbraco 7.5 yet, so have installed v7.0.0.1.
Just wanted to make sure that that's how it's supposed to look like, for example the "cleanup by count" and "cleanup by date" pages. (By the screen caps, the latest version looks much better :), we'll get to it in a while...)
thanks
![screenshot 86](https://user-images.githubusercontent.com/33389540/32413302-81343e4e-c217-11e7-975e-5aa3878fbda4.png)
![screenshot 85](https://user-images.githubusercontent.com/33389540/32413303-815e251a-c217-11e7-9194-d8a8e65f2f2b.png)

**Comment by afabri73** [comment]
Hello,
The version you have installed is an old version.
You must uninstall this version and download/install the last one.
N.B. Remember that the new version no more exist in developer section, but it work in a custom section and must be enable for users who can work with that.
