### ISSUE TITLE
FALM not showing up in Umbraco Back End

### ISSUE THREAD

**Issue by wilfriedjonker** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#39]
I have installed FALM version 7.6.0.9 on Umbraco 7.7.6 but it is not showing up. I did try to install it as Nuget and manually via the umbraco backend. Bot give the same result. 
![falm](https://user-images.githubusercontent.com/25723045/33015849-8816ba9e-cdec-11e7-88fe-0fe0b95a16ca.PNG)

**Comment by afabri73** [comment]
Hi Wilfried,
to view the new FALM section you must enable it for all users that need to use this tool.

Thank you for using my tool :-)
