### ISSUE TITLE
Install error "Could not find file package.xml"

### ISSUE THREAD

**Issue by jkirklen** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#4]
Trying to install this package today on Umbraco 7.2.8.  For some strange reason the package.xml file is not getting copied to the App_Data package folder.   I've adjusted permission on the App_Data folder to be sure all uses have Full Control.  Best i can tell all other files are being uploaded and I see package.xml in the package .zip file. Any suggestions?

Could not upload file
System.Exception: Error unpacking extension... ---> System.IO.FileNotFoundException: **Could not find file 'c:...\App_Data\03a6348f-4d29-4064-a1fb-2b02092daf3b\package.xml**'. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn) at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver) at System.Threading.CompressedStack.runTryCode(Object userData) at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData) at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state) at System.Xml.XmlTextReaderImpl.OpenUrl() at System.Xml.XmlTextReaderImpl.Read() at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace) at System.Xml.XmlDocument.Load(XmlReader reader) at System.Xml.XmlDocument.Load(String filename) at umbraco.cms.businesslogic.packager.Installer.LoadConfig(String tempDir) at umbraco.cms.businesslogic.packager.Installer.Import(String InputFile) --- End of inner exception stack trace --- at umbraco.cms.businesslogic.packager.Installer.Import(String InputFile) at umbraco.presentation.developer.packages.Installer.uploadFile(Object sender, EventArgs e)

**Comment by afabri73** [comment]
Hi jkirklen,
i don't know what is the problem...I only tell you to check the permissions on site's root folder.
Have you tried to enable "Network Service" and "IIS_IUSRS" users with full control to all folders and files?

**Comment by afabri73** [comment]
Try also to do this:
- Download again FALM Housekeeping v7.0.0.1
- Uninstall actual FALM Housekeeping from your website
- Right click on FALM_Housekeeping_7.0.0.1.zip and click on properties
- Go down at the end of the properties window (tab General)
- Check or push on "Unblock"
- Click Apply, then OK
- Try to reinstall FALM Housekeeping in your website
- Try to use log feature.

I think it should work.

I look forward to your reply
Adriano

**Comment by jkirklen** [comment]
Thanks for the reply.  I'm pretty sure Network Service has full control, but I'll check that.
I will also try steps below.

-----Original Message-----

**Comment by afabri73** [comment]
that's ok...please tell me if you'll solve!!!
Bye

**Comment by jkirklen** [comment]
Adriano,
I unblocked the zip file before installing and that seems to have solved the issue. 
Thanks

**Comment by jkirklen** [comment]
Hi Adriano,

I was able to install the package finally.  Unblocking the .zip file seemed to be the issue.

Everything seems to be working fine.  All of the options bring back results except that when I try and run the Media cleanup I never get any results.  When I click the “Show orphans to delete” it seems to start running, but it never comes back.  I don’t know if it is hanging or just never completing.  I don’t get any sort of error and I don’t see anything in the Umbraco logs.   The site I am running this on does have a lot of media items. 

Any ideas?  

Janet Kirklen

Pragmatx, Inc.

(w) 972-599-2989  (m) 214-673-9373

**Comment by afabri73** [comment]
Hi Janet,
I think that the problem is just the large amount of media.
I'would add a progress bar to solve this problem on a big media catague, but I'm very busy in this period and I don't know when I could finish.

Adriano
