### ISSUE TITLE
User Delete not working with the newer 7.7 tables

### ISSUE THREAD

**Issue by davidtwamley** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#40]
In Umbraco 7.7.6 (and I suspect starting at 7.7.1) there is an error when attempting to delete a user.

> Invalid object name 'umbracoUser2app'

They reworked a few tables. I think you would only need to delete from umbracoUser2UserGroup and umbracoUser2NodeNotify.

**Comment by afabri73** [comment]
Hi and sorry for delay.
I just published the new FALM version with the bug fix.
Thank you for the support.
Adriano
