### ISSUE TITLE
Access to the FALM v7.6.0.3 Branch

### ISSUE THREAD

**Issue by TFAstudio** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#42]
I have not been able to find/access the branch of code that was the v7.6.0.3 release.  I was wondering if there was a way you could tag/branch the version so I could download, test, and update where necessary?

Thanks

**Comment by afabri73** [comment]
Hello, the branch is the same "master", but you must find the right commit/release for v7.6.0.3

I found it for you.:
https://github.com/FALM-Umbraco-Projects/FALM-Housekeeping-v7/tree/d356dabd23059bec5a54796a3529b5a6fd04870b

Best Regards
