### ISSUE TITLE
Can't remove any versions

### ISSUE THREAD

**Issue by t9creative-zz** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#43]
On Umbraco 7.7.7.  Have successfully installed the package and enabled it for admins.  Section comes up fine and displays.

WHen I go to version control, and try any option, either all or by count or by a specific node, get the following javascript error:

Error: Duplicates in a repeater are not allowed. Repeater: item in dialogData.cleanupSummary key: string:l

**Comment by afabri73** [comment]
Hi,
sorry for delay.
I think there were more than one problem.
The first one is that I think you are using SQLCE as database. Unfortunately, as I wrote in the readme, the versions manager doesn't work properly with SQLCE. I'm trying to solve the problem but I still have not found a definitive solution.
The second one is that after push the "Cleanup all Versions" button, we always receive a red error banner. In this case I fixed the problem.
I tested it with umbraco v7.6.12 and v7.7.7 and MSSQL.

So...Now you can download the fixed FALM HK v7.7.0.1

Thank you for your support.
Adriano

**Comment by afabri73** [comment]
Versions Manager SQLCE compatibility issues are solved in the new release v7.7.0.2
