### ISSUE TITLE
Include datepicker styles affect Umbraco core datepicker

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#45]
I just noticed FALM Housekeeping package include its own datepicker3.less file, which affect the styles of the Umbraco core datepicker, e.g. to today table cell in the datepicker has a yellow color.

![image](https://user-images.githubusercontent.com/2919859/36425434-13630272-1647-11e8-9dcf-9eef2f035181.png)

![image](https://user-images.githubusercontent.com/2919859/36425456-2743876c-1647-11e8-9415-66fc0dfd095a.png)

Any reason for including the datepicker3.less file? I believe Umbraco already include the styles for the bootstrap datepicker. https://github.com/umbraco/Umbraco-CMS/blob/cf86409e3fec4198744189a48255543fc2f32614/src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/datepicker.controller.js#L115

**Comment by afabri73** [comment]
I need a date time picker in my package and the one included in Umbraco seems not working well.
So I downloaded and used the official bootstrap-datetimepicker.
I've donne some test in Umbraco to check if my custom files could create problems but all worked well...but honestly I didn't notice that it changed the style of Umbraco's original datapicker.
I'll try to remove (or modify ) the .map file that configure the own less file and I'll see if this solve the problem.

Thank you for the support

**Comment by bjarnef** [comment]
It should be possible to include the existing datepicker in a custom dashboard, section etc. and set the config based on your needs. I think the Umbraco datepicker i based on this project, but not the latest version. https://github.com/Eonasdan/bootstrap-datetimepicker

Something like this:

```
<umb-editor model="vm.datePicker.date"></umb-editor>
```

```
var vm = this;

vm.datePicker = {
       date: buildDateTimePickerModel('date', 'Date', 'Enter a date')
};

function buildDateTimePickerModel(alias, label, description) {
        return {
            editor: "Umbraco.DateTime",
            label: label,
            description: description,
            hideLabel: false,
            view: "datepicker",
            alias: alias,
            value: null,
            validation: {
                mandatory: false,
                pattern: ""
            },
            config: {
                format: "YYYY-MM-DD",
                pickDate: true,
                pickTime: false,
                useSeconds: false
            }
        };
    };
```

If you choose to include you own date(time) picker it is recommended to prefix it to avoid it from conflicting with core and other packages.

**Comment by afabri73** [comment]
Thank you for the info :+1: 
I'll try your code a.s.a.p. :sunglasses:

**Comment by afabri73** [comment]
Looking at code, it is an old configuration used by an old version of FALM HK (Version Manager).
I removed the call in the manifest and all function like a charm.

Soon I will publish the new version of my package with the update and a **new requested feature** :sunglasses:
