### ISSUE TITLE
Versions Manger has several issues

### ISSUE THREAD

**Issue by idseefeld** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#47]
1. onsingle node side bar first shows error message althoug it finally cleaned versions. After some time Success summery is displayed. But you have to update view by clicking Restart Search
2. **Cleanup all Versions** just throws timeout error.
3. **Cleanup versions by count** first shows generic error message. After some time an emtpy Success message is display, although nothing happened. In error logs you see timeout error.

**Comment by afabri73** [comment]
Can you tell me the Umbraco version and the FALM version you have?

Thanks

**Comment by afabri73** [comment]
Ok Dirk,
I tried all versions manager functions and I have no problems.
I used FALM v7.7.1.0 with Umbraco v7.9.2
See attached screenshots and I look forward to your reply.
Adriano

![falm 01](https://user-images.githubusercontent.com/6714121/37897957-da79e988-30e7-11e8-8b3b-b991bc1da30d.png)
![falm 02](https://user-images.githubusercontent.com/6714121/37897969-dd62ada6-30e7-11e8-8a80-06ea0ec0b234.png)
![falm 03](https://user-images.githubusercontent.com/6714121/37897975-e0532bc6-30e7-11e8-9f81-039d3ee3fed7.png)
![falm 04](https://user-images.githubusercontent.com/6714121/37897982-e264feb2-30e7-11e8-9407-2fdca4302b3f.png)
![falm 05](https://user-images.githubusercontent.com/6714121/37897986-e4ea0542-30e7-11e8-987b-4c28dd7dc533.png)
![falm 06](https://user-images.githubusercontent.com/6714121/37897991-e7995dc4-30e7-11e8-8ef4-f5c76a0acf93.png)
![falm 07](https://user-images.githubusercontent.com/6714121/37897996-e9aa274c-30e7-11e8-9986-371b905c5762.png)
![falm 08](https://user-images.githubusercontent.com/6714121/37897998-eba497ee-30e7-11e8-8026-da0d35a05ee0.png)
![falm 09](https://user-images.githubusercontent.com/6714121/37898007-f0b5b43e-30e7-11e8-9a33-eb9a84adc431.png)

**Comment by afabri73** [comment]
I close the issue in the meantime I waiting for your feedback.
I will reopen it as soon as I'll receive your message.

Adriano
