### ISSUE TITLE
No support for MySQL

### ISSUE THREAD

**Issue by mdima** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#5]
Hello, 
    do you think that supporting MySQL is something that might be included into FALM Housekeeping?

Thanks,
Michele

**Comment by afabri73** [comment]
Hi mdima,
sorry for enormous delay.
I'm working on a new version based on MVC...I think the next release is at the end of this year.

BTW...this package already use umbraco helper to connect to all DB supported by umbraco, then it already should work properly.

Please contact me if you still have problems.
Adriano
