### ISSUE TITLE
Missing dll when installing on .NET 4.5

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#50]
I installed latest version of the package v7.7.2.1 via NuGet, but I can't see the custom section.
I had a look at the files and it seems the dll is missing.

![image](https://user-images.githubusercontent.com/2919859/40727329-f388f248-6427-11e8-8912-8bd71263390d.png)

Or it might be because you have set the target version to .NET 4.6.1, so it doesn't include the dll for projects on e.g. .NET 4.5.2, which I think has been the default target version for Umbraco for a while.

![image](https://user-images.githubusercontent.com/2919859/40732879-a3c4c360-6434-11e8-89b1-c6d25a1f805c.png)

E.g. for UnVersion package it looks like this in NuGet explorer.

![image](https://user-images.githubusercontent.com/2919859/40732908-bfa8e426-6434-11e8-9210-132123154975.png)

and for Diplo Trace Log Viewer package.

![image](https://user-images.githubusercontent.com/2919859/40733433-eb3ddc80-6435-11e8-9d43-56455012eea5.png)

**Comment by bjarnef** [comment]
For now I have installed the package via Umbraco package installer.

**Comment by afabri73** [comment]
Thank you Bjarn,
I'll update the package asap.

Adriano

**Comment by afabri73** [comment]
Done.
The new release will include this change.
Thank you again for the support
Adriano
