### ISSUE TITLE
Hide "no results" while loading

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#51]
When accessing tree node "File System Cleanup" and requesting data, it show the "no results" panel and also the loader. It show hide this panel while loading. Furhtermore I don't think it show load on init since it might take a while for larger sites with a lot of media items, so I would prefer a button to start the search.

![image](https://user-images.githubusercontent.com/2919859/40744344-857b4f58-6454-11e8-80c4-36cda5abb3ef.png)

![image](https://user-images.githubusercontent.com/2919859/40744539-26a18f0a-6455-11e8-82b6-05dfc8dfd6e2.png)

For "Versions Manager" it just shows a "no results" panel on init and no loader - after about 5 seconds it change to the result list.

Make sure this is consistent in the different views.

**Comment by afabri73** [comment]
Thank you Bjarne for the support,
I'll correct the problems in next days.

Adriano

**Comment by afabri73** [comment]
Done.
The new release will include this change.
Thank you again for the support
Adriano
