### ISSUE TITLE
Disable checkbox for current user in users manager

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#52]
In Users Manager it shouldn't be possible to delete your own user. I haven't tried what would happen, but at least i think the checkbox should be disabled for the user currently logged in.

**Comment by afabri73** [comment]
Thank you Bjarne for the support,
In the users list the administrator and the current user should not appear but, as I see, it partially works.
The administrator doesn't appear but the current user is listed.
I will have to review the logic and hide the current user from the list.

Adriano

**Comment by afabri73** [comment]
Done...I updated the UsersManager to hide Super Admin and current logged user.
The new release will include this change.
Thank you again for the support
Adriano
