### ISSUE TITLE
Re-use core components/directives

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#53]
It would be nice if the package re-used core components/directives, e.g. `umb-overlay` for dialog and `umb-pagination` for pagination like it already use `umb-load-indicator`.

For pagination there is an example in Umbraco core here:
https://github.com/umbraco/Umbraco-CMS/blob/7ee510ed386495120666a78c61497f58ff05de8f/src/Umbraco.Web.UI.Client/src/views/common/overlays/userpicker/userpicker.html#L47-L54

**Comment by afabri73** [comment]
Thank you Bjarn,
sure...I'll update it asap.

Adriano

**Comment by afabri73** [comment]
I tried to use the UmbPagination directive but I'm finding a lot of problems.
I asked for help in our.umbraco.org ([https://our.umbraco.org/forum/extending-umbraco-and-using-the-api/92316-problems-using-umb-pagination](https://our.umbraco.org/forum/extending-umbraco-and-using-the-api/92316-problems-using-umb-pagination))

Did you already use the UmbPagination?
I need a big help!!!

**Comment by bjarnef** [comment]
@afabri73 yes, I have use in combination with the umb-table directive/component, but it should work with a regular table with ng-repeat since it is use on the redirects dashboard in Umbraco:

https://github.com/umbraco/Umbraco-CMS/blob/7ee510ed386495120666a78c61497f58ff05de8f/src/Umbraco.Web.UI.Client/src/views/dashboard/developer/redirecturls.html

**Comment by afabri73** [comment]
I don't know why the list is always unfiltered.
I'll try to use the umb-table instead of classic table.

P.S. Yesterday I released the new version of FALM HK ;-)

**Comment by afabri73** [comment]
Wonderful...now the DB Logs viewer works.
I used db.Page that paginate results in the SQL.

Now I'm trying to do the same with the Trace logs viewer...but for now the log list is not paged.
I used PagedResult<T> but it isn't working.

**Comment by bjarnef** [comment]
@afabri73 you should be able to do something like this https://github.com/umbraco/Umbraco-CMS/blob/324cd7e98f0c8ac8a92ed40fbfb7e9575eca863d/src/Umbraco.Core/Persistence/Repositories/AuditRepository.cs#L94-L96

or this in Redirects dashboard which also use `Database.Page` https://github.com/umbraco/Umbraco-CMS/blob/324cd7e98f0c8ac8a92ed40fbfb7e9575eca863d/src/Umbraco.Web/Editors/RedirectUrlManagementController.cs#L36-L59

or you could have a look at the *umbraco bulk user admin dashboard* package: https://github.com/leekelleher/umbraco-bulk-user-admin/blob/88eb6e20daad9e12373949d3142eef696da44dcb/src/Our.Umbraco.BulkUserAdmin/Web/Controllers/BulkUserAdminApiController.cs

**Comment by afabri73** [comment]
Hi Bjarn,
I've done all updates...now the Db and Trace Log Manager pagination function properly with the core component...but now I have a last big problem.
When I try to filter logs (using the intput field):

- the filter is applied "only" to the current page
- the pagination don't update

Do you know if there is a way to apply filter of all logs instead of only to the current Page (always using angular) and auto reorganize pagination?
I still don't know so well angular js.

**Comment by afabri73** [comment]
Now filter is applied for all pages but the pagination don't update.
I see always the original number of pages displayed when I open the page.

Do you know if there is a method to refresh the umb-pagination object?

**Comment by afabri73** [comment]
It has been very hard...but it seems all function properly!!! :-)

New release v7.7.2.5 is on nuget.
Now I'm update the package on github and our.umbraco

Adriano
