### ISSUE TITLE
Re-name section header "Menu"

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#54]
Currently the section root tree is named "Menu", which is very generic.
https://github.com/FALM-Umbraco-Projects/FALM-Housekeeping-v7/blob/33502ed1e6196ce4540e01e69d5cdba33956d8d9/FALMHousekeeping/Constants/HKConstants.cs#L34-L35

![image](https://user-images.githubusercontent.com/2919859/40745483-deaf8c62-6457-11e8-8055-7ba9b2212dd2.png)

I think it would be better to rename this to "FALM" or something similar. Most packages which add a custom section, use the project name as name of tree root.

**Comment by afabri73** [comment]
Thank you Bjarn,
I set "Menu" because the FALM text and Housekeeping text already appear in the content as title and subtitle.
I don't like to see redundant text...but I'll think about it.

Adriano

**Comment by afabri73** [comment]
Done.
The new release will include this change.
Thank you again for the support
Adriano
