### ISSUE TITLE
Cleanup by count doesn't show any loader

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#55]
When I use the "Cleanup by count" it doesn't show any loader, so you don't know if something is in progress:

![image](https://user-images.githubusercontent.com/2919859/40765249-29175394-64ac-11e8-8cb5-60f4b8b0a2fc.png)

All of the containers in the dialog has display:none;
![image](https://user-images.githubusercontent.com/2919859/40765364-80a3cbec-64ac-11e8-852f-16629b4d2b3a.png)

**Comment by bjarnef** [comment]
Cleanup all versions on a specific node doesn't work either.
And after this I can no longer save and publish nodes.

![image](https://user-images.githubusercontent.com/2919859/40765788-ece3e336-64ad-11e8-8891-0d47e225666f.png)

**Comment by bjarnef** [comment]
Now I don't have any "newest" version for frontpage node anymore.

![image](https://user-images.githubusercontent.com/2919859/40766145-ccea493e-64ae-11e8-862f-2ef088bee1de.png)

**Comment by afabri73** [comment]
Hi Bjarne,
about the loader...I tried to use the umbraco loader but it doesn't appear.
I still could not solve it...I tried something else but with no good results.

about Cleanup all versions...which umbraco version do you use? I tried non Umbraco v7.7.13 - v7.8.1 - v7.9.3 - v7.10.1 and it correctly works.

Adriano

**Comment by bjarnef** [comment]
If you are using `<umb-load-indicator ng-if="page.loading"></umb-load-indicator>` it should work.

Ensure to set a flag of the loading state, e.g. false on init, then true in the request and false in success/error after a short timeout.

You might also have a look at the DOM to ensure the loader is inside the dialog (maybe you need to ensure one of the parent element in the dialog has position: relative)

**Comment by afabri73** [comment]
Done.
The new release will include this change.
Thank you again for the support
Adriano
