### ISSUE TITLE
Does the package works with SQL CE

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#56]
Does this package works with SQL CE, which Umbraco Cloud use on local environment. Does it use SQL queries, which is not supported in SQL CE?

I tried the package on local environment, but it didn't seem cleanup version has any effect?

**Comment by afabri73** [comment]
I tried all funtions also with SQLCE (with VS2017) and they correctly work.

I'll try again to be sure

Adriano

**Comment by afabri73** [comment]
Yes It works
