### ISSUE TITLE
Update Nuget Package to support 7.11.x

### ISSUE THREAD

**Issue by suedeapple** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#57]
It would be great if the NUGET package was updated to support 7.11.x, as currently I am unable to install FALM on the latest umbraco version, due to a dependancy set on the Nuget package.

**Comment by afabri73** [comment]
I have had a little problems with v7.11
In the next days I'll try again to solve them and when I've done I'll upload the new release.
Adriano

**Comment by afabri73** [comment]
Done

**Comment by suedeapple** [comment]
Fantastic, doyou have a donate/patreon  page?

**Comment by suedeapple** [comment]
Hmmm, just tried it, however it does not seem to put the DLL in the bin folder.   Maybe I am doing something wrong.

**Comment by afabri73** [comment]
Hi,
I explore the nuget package and the FALM Housekeeping DLL is correctly in the lib/net452
Now I'm creating a new package with minimal difference.
I'll publish in a little while.
Try this new version

**Comment by suedeapple** [comment]
The DLL targets 4.5.2,  where as Umbraco is currently built against 4.5.

So your DLL wont get deployed, as you have put it in a net452 folder :-)

**Comment by suedeapple** [comment]
I changed the "targetframework" to 4.5.2 in web.config, and then re-install FALM from nuget, and the DLL got deployed to the /bin folder OK
