### ISSUE TITLE
Does FALM work with the new Umbraco media pickers?

### ISSUE THREAD

**Issue by lesley-w** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#58]
Just wondering if the File System cleanup takes account of media items that are saved as UDIs by the new Umbraco media pickers?
i.e.  umb://media/39d3ac707d634953ab52642d5037855c

Or does it just check for integer-based media items e.g.  /media/262188/ ?

**Comment by afabri73** [comment]
Hi lesley-w,
the current FALM HK version check only standard media items.
