### ISSUE TITLE
Not able view FLAM Section in Umbraco .

### ISSUE THREAD

**Issue by mann205t** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#59]
As I'm administrator user still unable to view / access FLAM section after installing it in umbraco v 7.7.0.

**Comment by afabri73** [comment]
The FALM section is not visible automatically after installation.
You must add the FALM Section manually to your group (I think is Administrators) and refresh the page by press f5 or the refresh button on the browser.

Hope this help
