### ISSUE TITLE
Versions | Clean up versions by date

### ISSUE THREAD

**Issue by lcichanowicz** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#63]
Greetings.  I would like to clean up version on a live site by removing all versions prior to go-live of the site.  I thought FALM could do this.  It appears I was wrong.  Or, was I?

Thanks,
Lee

**Comment by lcichanowicz** [comment]
Bummer.  It seems my recollection was correct, but my findings were also accurate.

https://github.com/FALM-Umbraco-Projects/FALM-Housekeeping-v7/issues/26

**Comment by lcichanowicz** [comment]
I think this may be my solution:
https://our.umbraco.com/packages/website-utilities/unversion

**Comment by afabri73** [comment]
Hi Lee,
can you tell me which version (FALM HK and Umbraco) you are using?

**Comment by lcichanowicz** [comment]
Thanks for the help, Adriano.  Sorry, I had my Umbraco version in the other issue, but not this one.

Umbraco 7.10.4
FALM Housekeeping 7.7.2.4

**Comment by afabri73** [comment]
OK...with the same configuration I haven't any problems in my local website (Umbraco v7.10.4 and FALMHK v7.7.2.4)
I'm using a Windows Server + MS SQL
I'm tried also with SQLCE

Which DB you are using?

**Comment by lcichanowicz** [comment]
SQL Server

**Comment by afabri73** [comment]
Hi tried to install a fresh copy of Umbraco v7.10.4 and install the latest version of FALM HK
I tried to install the package manually and by NuGet and in both cases I haven't problems.
In user groups I can add the FALM Section correctly.

Cheers
