### ISSUE TITLE
Filter by user dropdown diplay "any" twice

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#7]
It seems the "filter by user" dropdown display "-- Any --" twice. It is not an issue for the other filter dropdowns.

![image](https://cloud.githubusercontent.com/assets/2919859/21765016/8115e4c8-d666-11e6-9723-f99df8af4e84.png)

**Comment by afabri73** [comment]
I'm working (slowly) to a new version of FALM Housekeeping with Angular JS, but I'm very slow because I'm studying it now...thank you for your support, I'll implement the change in this release
