### ISSUE TITLE
Show versions - add count of versions

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#8]
When selecting "Show versions" and e.g. filtering by node id, can it have a count?
e.g. now it display:

```
Node name (Id: 2460 - Created: 18/01/2016 11:02)
```

Suggestion something like:

```
Node name (Id: 2460 - Created: 18/01/2016 11:02): xxx versions available
```

Furthermore maybe change the nodeId input to `<input type="number" min="0" />`

**Comment by afabri73** [comment]
I'm working (slowly) to a new version of FALM Housekeeping with Angular JS, but I'm very slow because I'm studying it now...thank you for your support, I'll implement the change in this release
