### ISSUE TITLE
Number of versions to keep doesn't allow 100+ versions

### ISSUE THREAD

**Issue by bjarnef** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#9]
The input for Number of versions to keep doesn't allow 100+ versions because it has `maxlength="2"` on the input.

On a site, which has grown the last couple of years, it has 592 version for homepage.
We would like to delete some of the oldest versions and e.g. only keep the latest 100 versions, but the input field only allow a max value of 99.

Furthermore consider to change the input to `<input type="number" min="2" max="500" />`

I guess it is okay to use minimum value 2, since you always have the latest versions (and the package has a note about Umbraco always keep the latest two versions). You could also change the max value, but not sure if it should limit administrator to keep e.g. latest 100 versions?

**Comment by bjarnef** [comment]
I could change the value or remove the attribute in DOM. After this I could delete all version except the latest 500 versions of each node.

![image](https://cloud.githubusercontent.com/assets/2919859/21766625/e7747fbe-d66f-11e6-96d0-3454bdcec60b.png)

Now my homepage node only has 500 versions - before 592.

![image](https://cloud.githubusercontent.com/assets/2919859/21766719/69b08c0c-d670-11e6-8143-87b8571d69ec.png)

![image](https://cloud.githubusercontent.com/assets/2919859/21766698/4a6f2650-d670-11e6-9502-164d7d66c918.png)

**Comment by afabri73** [comment]
I'm working (slowly) to a new version of FALM Housekeeping with Angular JS, but I'm very slow because I'm studying it now...thank you for your support, I'll implement the change in this release
